# Generated by Django 5.1.6 on 2025-03-05 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='seller',
            new_name='seller_id',
        ),
    ]
