# Generated by Django 5.1.6 on 2025-03-05 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_rename_seller_product_seller_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seller_id',
        ),
    ]
